#!/bin/bash

battery_state=$(cat /sys/class/power_supply/BAT0/status)

if [[ "${battery_state}" == "Discharging" || "${battery_state}" == "Charging" ]]; then
  battery_percent=$(cat /sys/class/power_supply/BAT0/capacity)
  echo "Bat ${battery_percent}%"
fi
