#!/bin/bash
ssid=$(nmcli -t -f active,ssid device wifi | grep '^yes' | cut -d: -f2)
statefile="/tmp/net_block_state"

if [[ ! -f "${statefile}" ]]; then
  echo "${ssid}" >${statefile}
fi

case "${BLOCK_BUTTON}" in
1) echo "$(hostname -I | awk '{print $1}')" >${statefile} ;;
2) echo "${ssid}" >${statefile} ;;
3) echo "$(hostname)" >${statefile} ;;
esac

cat "${statefile}"
